# Site settings
title: INFORA
email: contact@infora.life
url: https://infora.life
description: "We discover, you feel better"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#29b2b0'
  links: '#f8f8f8'

# Footer settings
footer: INFORA

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "terms"
    values:
      layout: "legal"
